### PR TITLE
Use a per-seed nonce value instead of RACE_SEED_MODIFIER

### PR DESCRIPTION
**Pull request by ianmcorvidae**
The nonce is generated from the microseconds part of the current timestamp during seed generation (for race seeds only) and stored in the database along with the other data. This makes it so you can't bypass the spoiler-log-free thing by knowing the RACE_SEED_MODIFIER and adding it to the seed string manually.

The migration is written to put the old RACE_SEED_MODIFIER into the database as the nonce value for older seeds, which means the database does not need to be blown away for this. I'm not even sure we strictly need to be storing the nonce value (seed generation just uses the stored pickles anyway), but I thought it would be better to store it.

### CODE REVIEW

**Comment by Anguirel86** [comment]
This could lead to two runners manually rolling a race seed with the same seed value and ending up with different randomization.  I like the idea of getting rid of the static RACE_SEED_MODIFIER (which is changed on the live server so it can't just be looked up by anyone), but is losing the ability to roll the same seed manually a problem for us?

**Comment by ianmcorvidae** [comment]
I'm not entirely sure, but I think it's better this way. I think that it becomes less and less potentially-problematic as we retain more seeds in the database, probably, since the links keep working. It also gets nicer if we add more seed-discovery features, if we add a user/login system (such that seed rollers can optionally see the spoiler log for race seeds -- at which point there's no reason we can't also allow seeing the nonce and setting the nonce in the form when needed in order to reproduce exactly).

**Comment by ianmcorvidae** [comment]
I guess one thing we might do to limit confusion is at least mark some sort of disclaimer on race seeds that explains how they work -- probably with or without this exact change. Something like a hover or question mark by the seed string that can be clicked, shown on the share link, that explains that this seed is modified in order to conceal the spoiler log, so it won't match other seeds rolled with the same string (whether with or without the race seed toggle on).

**Comment by ianmcorvidae** [comment]
Ah, also, with the changed `RACE_SEED_MODIFIER` on the live server, we may want to go in and manually fix the nonces in the DB; the migration I added won't work properly for that case.

(glad to see it's not set to the default on the live server anymore though!)

**Pull request merged**
